# server기본 설정
server:
  port: 8081
  servlet:
    contextPath: /

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true  # Swagger 문서를 생성할지 여부 (기본값: true)
    path: /api-docs/json  # 생성된 API 문서의 경로를 지정
    groups:
      enabled: true  # 그룹별로 API 문서를 생성할지 여부 (기본값: true)
  cache:
    disabled: true  # Swagger 문서의 캐싱을 사용하지 않도록 설정 (기본값: false)
  # 기본적으로 사용할 요청 및 응답의 미디어 타입을 설정
  default-produces-media-type: application/json;charset=UTF-8
  default-consumes-media-type: application/json;charset=UTF-8
  packages-to-scan: com.dev.hobby.user.controller # Swagger 문서를 생성할 컨트롤러가 포함된 패키지를 지정
  paths-to-match: /**  # 문서화할 경로를 지정합니다. /**는 모든 경로를 의미

# Spring Boot 기본 설정
spring:

  data:
    mongodb:
#      uri: "mongodb://root:!q@w#e$r@localhost:27017/users"
      uri: "mongodb://root:root1234@localhost:27017/users?authSource=admin"

  datasource:
    url: "jdbc:p6spy:mysql://localhost:3306/users"
    username: "root"
    password: "root1234"
    driver-class-name: "com.p6spy.engine.spy.P6SpyDriver"

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: false
    hibernate:
      format_sql: true
      use_sql_comments: true
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  logging:
    level:
      com.p6spy: DEBUG


---
# --------------------------------------------------
# 로컬(dummyData)
# 속성 값을 정의 하거나 공통 속성 값을 재정의 합니다.
# --------------------------------------------------
spring:
  config:
    activate:
      on-profile: local, default

server:
  port: 8082
